name: CI

on: [push, pull_request]

jobs:
  ci:
    container: rust:1.41
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        feature: ["", "--features \"dump\""]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          apt-get update
          apt-get install -y clang
          rustup component add rustfmt-preview
      - name: Build
        run: cargo build ${{ matrix.feature }} --release
      - name: Run unit tests
        run: cargo test --lib ${{ matrix.feature }} --release -v --no-fail-fast -- --nocapture --test
      - name: Run documentation tests
        run: cargo test --doc ${{ matrix.feature }} --release -v --no-fail-fast -- --nocapture --test
      - name: Run integration tests
        run: cargo test --test tapyrus-signer ${{ matrix.feature }} --release -v --no-fail-fast -- --nocapture --test
      - name: Run benchmark tests
        run: cargo test --lib ${{ matrix.feature }} --release -v --no-fail-fast -- --nocapture --bench
      - name: Check Format
        run: cargo fmt --verbose --all -- --check --verbose

